---
# Main Ansible Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      
    - name: Start Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure App Servers
  hosts: appservers
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - nodejs
          - npm
        state: present
        update_cache: yes
      
    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        mode: '0755'

- name: Configure Database Servers
  hosts: dbservers
  become: true
  tasks:
    - name: Install MySQL
      apt:
        name: 
          - mysql-server
          - python3-pymysql
        state: present
        update_cache: yes
      
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes 