---
# Staging Environment Inventory

all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.1.1.10
        web02:
          ansible_host: 10.1.1.11
    appservers:
      hosts:
        app01:
          ansible_host: 10.1.10.10
        app02:
          ansible_host: 10.1.10.11
    dbservers:
      hosts:
        db01:
          ansible_host: 10.1.10.20

    databases:
      hosts:
        db-staging-01:
          ansible_host: 10.1.2.10
        db-staging-02:
          ansible_host: 10.1.2.11

    monitoring:
      hosts:
        monitor-staging-01:
          ansible_host: 10.1.3.10

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/staging_key.pem
    environment: staging
