---
# Webserver Configuration Tasks

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags: [install, webserver]
      
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx
  tags: [config, webserver]

- name: Enable and start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags: [service, webserver]

- name: Create web content directory
  file:
    path: "{{ web_content_dir | default('/var/www/html') }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  tags: [setup, webserver] 