---
# Monitoring Role Handlers

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
