---
# Production Environment Inventory

all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.2.1.10
        web02:
          ansible_host: 10.2.1.11
        web03:
          ansible_host: 10.2.1.12
    appservers:
      hosts:
        app01:
          ansible_host: 10.2.10.10
        app02:
          ansible_host: 10.2.10.11
        app03:
          ansible_host: 10.2.10.12
    dbservers:
      hosts:
        db01:
          ansible_host: 10.2.10.20
        db02:
          ansible_host: 10.2.10.21

    databases:
      children:
        primary:
          hosts:
            db-prod-primary:
              ansible_host: 10.2.2.10
        replicas:
          hosts:
            db-prod-replica-01:
              ansible_host: 10.2.2.11
            db-prod-replica-02:
              ansible_host: 10.2.2.12

    monitoring:
      hosts:
        monitor-prod-01:
          ansible_host: 10.2.3.10
        monitor-prod-02:
          ansible_host: 10.2.3.11

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/prod_key.pem
    env_type: prod


