---
# Monitoring Server Configuration Tasks

- name: Install Prometheus
  apt:
    name: prometheus
    state: present
    update_cache: yes
  tags: [install, monitoring]

- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present
  tags: [install, monitoring]

- name: Install Grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_9.3.2_amd64.deb
  tags: [install, monitoring]

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart prometheus
  tags: [config, monitoring]

- name: Configure Grafana datasources
  template:
    src: datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yml
    owner: grafana
    group: grafana
    mode: '0640'
  notify: restart grafana
  tags: [config, monitoring]

- name: Configure Grafana dashboards
  template:
    src: dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
    owner: grafana
    group: grafana
    mode: '0640'
  notify: restart grafana
  tags: [config, monitoring]

- name: Ensure Prometheus is running
  service:
    name: prometheus
    state: started
    enabled: yes
  tags: [service, monitoring]

- name: Ensure Grafana is running
  service:
    name: grafana-server
    state: started
    enabled: yes
  tags: [service, monitoring] 