---
# Monitoring Role Tasks

- name: Install monitoring dependencies
  ansible.builtin.apt:
    name:
      - prometheus
      - prometheus-node-exporter
    state: present
    update_cache: true
  tags: [install, monitoring]

- name: Install Grafana repository signing key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  tags: [install, monitoring]

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  tags: [install, monitoring]

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
  tags: [install, monitoring]

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus
  tags: [config, monitoring]

- name: Configure Grafana datasources
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yml
    owner: grafana
    group: grafana
    mode: '0640'
  notify: Restart Grafana
  tags: [config, monitoring]

- name: Configure Grafana dashboards
  ansible.builtin.template:
    src: dashboards.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
    owner: grafana
    group: grafana
    mode: '0640'
  notify: Restart Grafana
  tags: [config, monitoring]

- name: Start and enable Prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
  tags: [service, monitoring]

- name: Start and enable Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
  tags: [service, monitoring]

