#!/bin/bash
#
# CI/CD Connection Test Script
# A simple test to verify CI/CD pipeline connectivity and functionality
#

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "========================================================"
echo "             CI/CD Connection Test Script"
echo "========================================================"

# Get the date and time for the report
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
HOSTNAME=$(hostname)
USER=$(whoami)

# Check GitHub Actions configuration
if [ -d ".github/workflows" ]; then
    WORKFLOW_FILES=$(find .github/workflows -name "*.yml" | wc -l)
    echo -e "\n${GREEN}GitHub Actions workflows found:${NC} $WORKFLOW_FILES"
    
    # List all workflow files
    echo -e "\nWorkflow files:"
    for file in $(find .github/workflows -name "*.yml"); do
        echo "  - $file"
    done
else
    echo -e "\n${RED}No GitHub Actions workflows found.${NC}"
fi

# Create a test report
echo -e "\nGenerating test report..."

REPORT_DIR="reports"
mkdir -p $REPORT_DIR
REPORT_FILE="$REPORT_DIR/cicd_connection_test_$(date +%Y%m%d%H%M%S).txt"

cat > $REPORT_FILE << EOF
CI/CD CONNECTION TEST REPORT
===========================
Timestamp: $TIMESTAMP
Hostname: $HOSTNAME
User: $USER

Environment Information
----------------------
OS: $(uname -a)
Shell: $SHELL
Path: $PATH

GitHub Actions Configuration
---------------------------
Workflow files: $WORKFLOW_FILES

Test Status
----------
✅ Test execution: SUCCESS
✅ Report generation: SUCCESS

This file was automatically generated by the CI/CD connection test script.
EOF

echo -e "${GREEN}Test report generated:${NC} $REPORT_FILE"

# Print summary
echo -e "\n========================================================"
echo "                       SUMMARY"
echo "========================================================"
echo -e "${GREEN}✅ CI/CD Connection Test PASSED${NC}"
echo -e "The CI/CD connection test completed successfully."
echo -e "A test report was generated at: ${YELLOW}$REPORT_FILE${NC}"
echo -e "\nThis test verifies that your CI/CD environment has the necessary"
echo -e "access and permissions to execute operations on this repository."
echo "========================================================" 