---
# Development Environment Inventory

all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
        web02:
          ansible_host: 10.0.1.11
    appservers:
      hosts:
        app01:
          ansible_host: 10.0.10.10
        app02:
          ansible_host: 10.0.10.11
    dbservers:
      hosts:
        db01:
          ansible_host: 10.0.10.20

    databases:
      hosts:
        db-dev-01:
          ansible_host: 10.0.2.10

    monitoring:
      hosts:
        monitor-dev-01:
          ansible_host: 10.0.3.10

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/dev_key.pem
    environment: dev
