---
# Webserver Role Default Variables

# Content Configuration
webserver_web_content_dir: "/var/www/html"

# Nginx Configuration
webserver_nginx_worker_processes: "auto"
webserver_nginx_worker_connections: 1024
webserver_nginx_keepalive_timeout: 65
webserver_nginx_client_max_body_size: "1m"
