---
# Main Ansible Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Start Nginx Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

- name: Configure App Servers
  hosts: appservers
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: true
    
    - name: Create app directory
      ansible.builtin.file:
        path: /opt/app
        state: directory
        mode: '0755'

- name: Configure Database Servers
  hosts: dbservers
  become: true
  tasks:
    - name: Install MySQL
      ansible.builtin.apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present
        update_cache: true
    
    - name: Start MySQL Service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
