---
# Application Server Tasks

- name: Install Node.js and npm
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: true
  tags: [install, appserver]

- name: Create application directory
  ansible.builtin.file:
    path: "{{ appserver_app_dir }}"
    state: directory
    owner: "{{ appserver_app_user }}"
    group: "{{ appserver_app_group }}"
    mode: '0755'
  tags: [setup, appserver]

- name: Install PM2 globally
  community.general.npm:
    name: pm2
    global: true
    state: present
  tags: [install, appserver]

- name: Configure application environment
  ansible.builtin.template:
    src: env.j2
    dest: "{{ appserver_app_dir }}/.env"
    owner: "{{ appserver_app_user }}"
    group: "{{ appserver_app_group }}"
    mode: '0600'
  notify: Restart Application
  tags: [config, appserver]

- name: Configure PM2 application
  ansible.builtin.template:
    src: ecosystem.config.js.j2
    dest: "{{ appserver_app_dir }}/ecosystem.config.js"
    owner: "{{ appserver_app_user }}"
    group: "{{ appserver_app_group }}"
    mode: '0644'
  notify: Restart Application
  tags: [config, appserver]

- name: Setup application systemd service
  ansible.builtin.template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags: [service, appserver]
