---
# Development Environment Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  vars:
    environment: dev
  roles:
    - { role: dev/webserver, tags: [webserver] }

- name: Configure App Servers
  hosts: appservers
  become: true
  vars:
    environment: dev
  roles:
    - { role: dev/appserver, tags: [appserver] }

- name: Configure Database Servers
  hosts: dbservers
  become: true
  vars:
    environment: dev
  roles:
    - { role: dev/database, tags: [database] }

- name: Configure Monitoring
  hosts: monitoring
  become: true
  vars:
    environment: dev
  roles:
    - { role: dev/monitoring, tags: [monitoring] }
