---
# Development Environment Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  vars:
    env_type: dev
  roles:
    - role: webserver
      tags: [webserver]

- name: Configure App Servers
  hosts: appservers
  become: true
  vars:
    env_type: dev
  roles:
    - role: appserver
      tags: [appserver]

- name: Configure Database Servers
  hosts: dbservers
  become: true
  vars:
    env_type: dev
  roles:
    - role: database
      tags: [database]

- name: Configure Monitoring
  hosts: monitoring
  become: true
  vars:
    env_type: dev
  roles:
    - role: monitoring
      tags: [monitoring]
