---
# Monitoring Role Default Variables

# Prometheus Configuration
monitoring_prometheus_global_scrape_interval: "15s"
monitoring_prometheus_global_evaluation_interval: "15s"
monitoring_prometheus_alertmanager_timeout: "10s"

# Grafana Configuration
monitoring_grafana_admin_user: "admin"
monitoring_grafana_admin_password: "changeme"
monitoring_grafana_install_plugins:
  - "grafana-clock-panel"
  - "grafana-simple-json-datasource"

# Node Exporter Configuration
monitoring_prometheus_node_exporter_targets:
  - "localhost:9100"
