---
# Staging Environment Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  vars:
    env_type: "staging"
  roles:
    - { role: staging/webserver, tags: [webserver] }

- name: Configure App Servers
  hosts: appservers
  become: true
  vars:
    env_type: "staging"
  roles:
    - { role: common/appserver, tags: [appserver] }

- name: Configure Database Servers
  hosts: dbservers
  become: true
  vars:
    env_type: "staging"
  roles:
    - { role: common/database, tags: [database] }

- name: Configure Monitoring
  hosts: monitoring
  become: true
  vars:
    env_type: "staging"
  roles:
    - { role: common/monitoring, tags: [monitoring] }
