---
# Staging Environment Playbook
- name: Configure Web Servers
  hosts: webservers
  become: true
  vars:
    environment: staging
  roles:
    - { role: staging/webserver, tags: [webserver] }

- name: Configure App Servers
  hosts: appservers
  become: true
  vars:
    environment: staging
  roles:
    - { role: staging/appserver, tags: [appserver] }

- name: Configure Database Servers
  hosts: dbservers
  become: true
  vars:
    environment: staging
  roles:
    - { role: staging/database, tags: [database] }

- name: Configure Monitoring
  hosts: monitoring
  become: true
  vars:
    environment: staging
  roles:
    - { role: staging/monitoring, tags: [monitoring] } 