---
# Monitoring defaults

# Prometheus configuration
prometheus_global_scrape_interval: 15s
prometheus_global_evaluation_interval: 15s
prometheus_alertmanager_timeout: 10s

# Grafana configuration
grafana_admin_user: admin
grafana_admin_password: admin
grafana_install_plugins:
  - grafana-clock-panel
  - grafana-piechart-panel

# Targets
prometheus_node_exporter_targets:
  - targets: []  # Will be populated from Terraform outputs 