---
# Webserver Role Tasks for Staging Environment

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  
- name: Start Nginx Service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx for staging
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx 