name: Ansible Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ansible/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    name: Ansible Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint ansible/ 