name: CI/CD Connection Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  connection-test:
    name: CI/CD Connection Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Repository Validation
        run: |
          chmod +x ./scripts/validate_repo.sh
          ./scripts/validate_repo.sh
        
      - name: Test Environment
        run: |
          echo "==================================================================="
          echo "CI/CD Connection Test"
          echo "==================================================================="
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "==================================================================="
          echo "✅ CI/CD Connection Test PASSED!"
          echo "===================================================================" 